### ISSUE TITLE
Invalid license ID in plugin.json

### ISSUE THREAD

**Issue by cschol** [64MM4-KN1F3/AuntyLangtons-FREE#1]
```
[AuntyLangtons-FREE] Issues found in `plugin.json`:

authorUrl: no URL specified
Invalid license ID: 
-- License must be a valid Identifier from https://spdx.org/licenses/
```

**Comment by 64MM4-KN1F3** [comment]
@cschol - I have added GPL-v3 license details including plugin.json update.

Commit hash: f28a4ec414224e61bbbf40d052432bdf1ea50cbd

**Comment by 64MM4-KN1F3** [comment]
@cschol - oops. Sorry, typo. Fixed.

Commit hash: 49465db849a79225527a152c9e8427bda83da177

**Comment by cschol** [comment]
Fixed. Thanks.
